export const FADI_PASTA = "LOOK YOU PIECE OF SHIT NO ONE PRANKS ME AND IM " + 
                  "NOT YOUR LITTLE ASS TO BUY FOR YOU OR THE OTHERS PIZZA " + 
                  "AND I DONT EVEN CARE IF ITS YOU OR ANYBODY'S ELSE THAT " + 
                  "CAME UP WITH THIS IDEA SO NOW YOU JUST LOST A FRIEND " + 
                  "THAT REALLY FUCKIN CARED BUT HE WASNT REALIZING THAT " + 
                  "THEY REALLY HATE ME  ...... MY LAST THING THAT I WANT " + 
                  "TO SAY I WISH YOU CAN DO THIS ON YOUR TRUE FRIENDS AND " + 
                  "SEE WHAT THE FUCK THEY FEEL SEE YA ASS HOLE";

export const CANDLE_VIDEO = "https://www.youtube.com/watch?v=XL73jjKGcb0";